"""
Tool schema definitions for the Telegram bot LLM function-calling system.

Each ToolDef gives the LLM precise information about:
  - What the tool does (description)
  - What parameters it accepts (params)
  - An OpenAI-format JSON schema for native tool calling

Tools are registered alongside their Python handlers in the orchestrator
and rendered as both OpenAI tool schemas (for native tool calling via Ollama)
and as human-readable docs for the text fallback path.

Ollama/llama3.1:8b supports OpenAI-compatible tool calling. This module
enables that path so the model can invoke internal APIs reliably rather than
trying to parse text ACTION: lines.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any, Optional


# ============================================================================
# Schema building blocks
# ============================================================================

@dataclass
class ParamDef:
    """Definition of a single tool parameter."""
    name: str
    type: str           # "string" | "number" | "integer" | "boolean" | "array"
    description: str
    required: bool = False
    default: Any = None
    enum: Optional[list] = None  # Restrict to specific values


@dataclass
class ToolDef:
    """
    Schema definition for a callable tool exposed to the LLM.

    Supports both:
      1. OpenAI-format tool calling (preferred — native, structured)
      2. Text fallback: ACTION:name|param=value prompt injection
    """
    name: str
    description: str
    category: str = "general"           # Groups tools in fallback prompt
    params: list[ParamDef] = field(default_factory=list)

    # ── OpenAI tool-call schema ──────────────────────────────────────────────

    def to_openai_schema(self) -> dict:
        """
        Return this tool as an OpenAI-compatible function schema dict.
        Pass directly to ``tools=`` in chat.completions.create().
        """
        properties: dict[str, Any] = {}
        required_params: list[str] = []

        for p in self.params:
            schema: dict[str, Any] = {
                "type": p.type,
                "description": p.description,
            }
            if p.enum:
                schema["enum"] = p.enum
            if p.default is not None:
                schema["default"] = p.default
            properties[p.name] = schema
            if p.required:
                required_params.append(p.name)

        return {
            "type": "function",
            "function": {
                "name": self.name,
                "description": self.description,
                "parameters": {
                    "type": "object",
                    "properties": properties,
                    "required": required_params,
                },
            },
        }

    # ── Fallback text-prompt rendering ──────────────────────────────────────

    def to_prompt_lines(self) -> list[str]:
        """Compact tool description for the text-based fallback prompt."""
        lines = [f"• {self.name} — {self.description}"]
        for p in self.params:
            marker = "required" if p.required else f"default={p.default!r}"
            enum_hint = f", one of {p.enum}" if p.enum else ""
            lines.append(
                f"    {p.name} ({p.type}, {marker}{enum_hint}): {p.description}"
            )
        return lines


# ============================================================================
# Pre-built ToolDef catalogue
#
# These are imported by the orchestrator when wiring up the chat handler.
# Any tool NOT in this catalogue falls back to a bare no-params schema.
# ============================================================================

# ── Read / status ────────────────────────────────────────────────────────────

TOOL_GET_STATUS = ToolDef(
    name="get_status",
    description="Get full portfolio snapshot: value, return, PnL, drawdown, open positions, pause/circuit-breaker state.",
    category="status",
)

TOOL_GET_BALANCE = ToolDef(
    name="get_balance",
    description="Get portfolio value, cash balance, return pct, and total PnL.",
    category="status",
)

TOOL_GET_POSITIONS = ToolDef(
    name="get_positions",
    description="List all open positions with quantities and current prices.",
    category="status",
)

TOOL_GET_CURRENT_PRICES = ToolDef(
    name="get_current_prices",
    description="Get the latest prices for all tracked trading pairs.",
    category="status",
)

TOOL_GET_RECENT_TRADES = ToolDef(
    name="get_recent_trades",
    description="Get the most recent trades executed by the agent.",
    category="status",
)

TOOL_GET_RECENT_SIGNALS = ToolDef(
    name="get_recent_signals",
    description="Get the latest trading signals generated by the market analyst, with confidence scores.",
    category="status",
)

TOOL_GET_FEAR_GREED = ToolDef(
    name="get_fear_greed",
    description="Get the current Crypto Fear & Greed Index value and label.",
    category="status",
)

TOOL_GET_NEWS_SUMMARY = ToolDef(
    name="get_news_summary",
    description="Get a summary of the latest aggregated crypto news articles.",
    category="status",
)

TOOL_GET_PENDING_SWAPS = ToolDef(
    name="get_pending_swaps",
    description="List pending portfolio rotation swap proposals with expected net gains.",
    category="status",
)

TOOL_GET_HIGHSTAKES_STATUS = ToolDef(
    name="get_highstakes_status",
    description="Get whether high-stakes mode is active, its expiry time, and elevated limits.",
    category="status",
)

TOOL_GET_ROTATION_ANALYSIS = ToolDef(
    name="get_rotation_analysis",
    description="Run a fresh portfolio rotation analysis to identify swap opportunities right now.",
    category="status",
)

TOOL_GET_TRAILING_STOPS = ToolDef(
    name="get_trailing_stops",
    description="List all active trailing stops with their pair, trigger price, and distance.",
    category="status",
)

# ── Analytics ────────────────────────────────────────────────────────────────

TOOL_GET_STATS = ToolDef(
    name="get_stats",
    description="Get performance statistics (trades, win-rate, PnL, fees) for the past N hours.",
    category="analytics",
    params=[
        ParamDef("hours", "integer", "Look-back window in hours.", default=24),
    ],
)

TOOL_GET_TRADE_HISTORY = ToolDef(
    name="get_trade_history",
    description="Get detailed trade history for the past N hours, optionally filtered by pair.",
    category="analytics",
    params=[
        ParamDef("hours", "integer", "Look-back window in hours.", default=24),
        ParamDef("pair", "string", "Filter by trading pair, e.g. BTC-USD.", default=None),
    ],
)

TOOL_GET_PAIR_STATS = ToolDef(
    name="get_pair_stats",
    description="Get statistics for a specific trading pair over the past N hours.",
    category="analytics",
    params=[
        ParamDef("pair", "string", "Trading pair e.g. BTC-USD.", required=True),
        ParamDef("hours", "integer", "Look-back window in hours.", default=168),
    ],
)

TOOL_GET_BEST_WORST = ToolDef(
    name="get_best_worst",
    description="Get the best and worst individual trades over the past N hours.",
    category="analytics",
    params=[
        ParamDef("hours", "integer", "Look-back window in hours.", default=168),
    ],
)

TOOL_GET_DAILY_SUMMARIES = ToolDef(
    name="get_daily_summaries",
    description="Get daily P&L summaries for the past N days.",
    category="analytics",
    params=[
        ParamDef("days", "integer", "Number of days to fetch.", default=7),
    ],
)

TOOL_GET_SCHEDULES = ToolDef(
    name="get_schedules",
    description="List all active scheduled reports.",
    category="analytics",
)

# ── Config / settings ────────────────────────────────────────────────────────

TOOL_GET_CONFIG = ToolDef(
    name="get_config",
    description=(
        "Read all current runtime configuration: absolute rules, trading params, "
        "risk params, fee settings, and active trading pairs."
    ),
    category="config",
)

TOOL_UPDATE_RULE = ToolDef(
    name="update_rule",
    description=(
        "Update an absolute trading rule at runtime. Changes take effect immediately "
        "and are logged. Does NOT persist to disk — restart resets to settings.yaml values."
    ),
    category="config",
    params=[
        ParamDef(
            "param", "string",
            "Rule to update.",
            required=True,
            enum=[
                "max_single_trade_usd",
                "max_daily_spend_usd",
                "max_daily_loss_usd",
                "max_portfolio_risk_pct",
                "require_approval_above_usd",
                "min_trade_interval_seconds",
                "max_trades_per_day",
                "max_cash_per_trade_pct",
                "emergency_stop_portfolio_usd",
                "always_use_stop_loss",
                "max_stop_loss_pct",
            ],
        ),
        ParamDef("value", "string", "New value for the parameter (will be cast to appropriate type).", required=True),
    ],
)

TOOL_UPDATE_TRADING_PARAM = ToolDef(
    name="update_trading_param",
    description=(
        "Update a trading parameter at runtime. Changes take effect immediately. "
        "Does NOT persist to settings.yaml."
    ),
    category="config",
    params=[
        ParamDef(
            "param", "string",
            "Parameter to update.",
            required=True,
            enum=[
                "min_confidence",
                "max_open_positions",
                "interval",
                "paper_slippage_pct",
            ],
        ),
        ParamDef("value", "string", "New value (will be cast to appropriate type).", required=True),
    ],
)

TOOL_UPDATE_RISK_PARAM = ToolDef(
    name="update_risk_param",
    description=(
        "Update a risk management parameter at runtime. "
        "Does NOT persist to settings.yaml."
    ),
    category="config",
    params=[
        ParamDef(
            "param", "string",
            "Risk parameter to update.",
            required=True,
            enum=[
                "stop_loss_pct",
                "take_profit_pct",
                "trailing_stop_pct",
                "max_position_pct",
                "max_total_exposure_pct",
                "max_drawdown_pct",
                "max_trades_per_hour",
                "loss_cooldown_seconds",
            ],
        ),
        ParamDef("value", "string", "New value.", required=True),
    ],
)

TOOL_ADD_PAIR = ToolDef(
    name="add_pair",
    description="Add a trading pair to the active pairs list (e.g. SOL-USD).",
    category="config",
    params=[
        ParamDef("pair", "string", "Trading pair in COIN-USD format, e.g. SOL-USD.", required=True),
    ],
)

TOOL_REMOVE_PAIR = ToolDef(
    name="remove_pair",
    description="Remove a trading pair from the active pairs list.",
    category="config",
    params=[
        ParamDef("pair", "string", "Trading pair to remove, e.g. ATOM-USD.", required=True),
    ],
)

TOOL_BLACKLIST_PAIR = ToolDef(
    name="blacklist_pair",
    description="Add a pair to the never-trade blacklist (absolute rule). Takes effect immediately.",
    category="config",
    params=[
        ParamDef("pair", "string", "Trading pair to blacklist, e.g. DOGE-USD.", required=True),
    ],
)

TOOL_UNBLACKLIST_PAIR = ToolDef(
    name="unblacklist_pair",
    description="Remove a pair from the never-trade blacklist.",
    category="config",
    params=[
        ParamDef("pair", "string", "Trading pair to unblacklist.", required=True),
    ],
)

# ── Trading actions ──────────────────────────────────────────────────────────

TOOL_PAUSE_TRADING = ToolDef(
    name="pause_trading",
    description="Pause all trading immediately. Analysis still runs but no orders are placed.",
    category="control",
)

TOOL_RESUME_TRADING = ToolDef(
    name="resume_trading",
    description="Resume trading after a pause.",
    category="control",
)

TOOL_EMERGENCY_STOP = ToolDef(
    name="emergency_stop",
    description="EMERGENCY STOP — halts all trading and closes the trading loop. Requires restart to resume.",
    category="control",
)

TOOL_ENABLE_HIGHSTAKES = ToolDef(
    name="enable_highstakes",
    description="Activate high-stakes mode for a defined duration, raising trade size limits.",
    category="control",
    params=[
        ParamDef("duration", "string", "Duration string e.g. 4h, 2h, 30m.", default="4h"),
    ],
)

TOOL_DISABLE_HIGHSTAKES = ToolDef(
    name="disable_highstakes",
    description="Deactivate high-stakes mode immediately, returning to normal limits.",
    category="control",
)

TOOL_APPROVE_ITEM = ToolDef(
    name="approve_item",
    description="Approve a pending trade or swap that is awaiting confirmation.",
    category="control",
    params=[
        ParamDef("item_id", "string", "The trade or swap ID to approve.", required=True),
    ],
)

TOOL_REJECT_ITEM = ToolDef(
    name="reject_item",
    description="Reject a pending trade or swap that is awaiting confirmation.",
    category="control",
    params=[
        ParamDef("item_id", "string", "The trade or swap ID to reject.", required=True),
    ],
)

TOOL_CANCEL_SWAP = ToolDef(
    name="cancel_swap",
    description="Cancel a specific pending rotation swap proposal.",
    category="control",
    params=[
        ParamDef("swap_id", "string", "The swap ID to cancel.", required=True),
    ],
)

TOOL_CREATE_TASK = ToolDef(
    name="create_task",
    description="Create a one-shot task for the agent to watch for and execute when conditions are met.",
    category="control",
    params=[
        ParamDef("description", "string", "Task description e.g. 'Buy BTC if price drops below 90k, max $500'.", required=True),
    ],
)

# ── Reporting / scheduling ───────────────────────────────────────────────────

TOOL_SCHEDULE_REPORT = ToolDef(
    name="schedule_report",
    description="Schedule a recurring report to be sent via Telegram.",
    category="reporting",
    params=[
        ParamDef("name", "string", "Report name.", required=True),
        ParamDef("interval", "string", "Interval: Nh (hours), Nm (minutes), Nd (days), e.g. 1h.", default="1h"),
        ParamDef("query_type", "string", "What to report.", default="performance", enum=["performance", "pair_stats", "trades", "portfolio_history"]),
        ParamDef("pair", "string", "For pair_stats: which pair.", default=None),
        ParamDef("hours", "integer", "Look-back window in hours.", default=24),
    ],
)

TOOL_DELETE_SCHEDULE = ToolDef(
    name="delete_schedule",
    description="Delete a scheduled report by its ID.",
    category="reporting",
    params=[
        ParamDef("id", "integer", "Schedule ID to delete.", required=True),
    ],
)

TOOL_GET_TRADING_RULES = ToolDef(
    name="get_trading_rules",
    description="Get a human-readable summary of all absolute rules and their current daily counters.",
    category="status",
)

TOOL_GET_FEE_INFO = ToolDef(
    name="get_fee_info",
    description="Get current fee configuration, breakeven thresholds, and fee estimates.",
    category="status",
)


# ============================================================================
# Registry — maps tool name → ToolDef
# ============================================================================

_BUILTIN_TOOLS: list[ToolDef] = [
    TOOL_GET_STATUS, TOOL_GET_BALANCE, TOOL_GET_POSITIONS, TOOL_GET_CURRENT_PRICES,
    TOOL_GET_RECENT_TRADES, TOOL_GET_RECENT_SIGNALS, TOOL_GET_FEAR_GREED,
    TOOL_GET_NEWS_SUMMARY, TOOL_GET_PENDING_SWAPS, TOOL_GET_HIGHSTAKES_STATUS,
    TOOL_GET_ROTATION_ANALYSIS, TOOL_GET_TRAILING_STOPS,
    TOOL_GET_STATS, TOOL_GET_TRADE_HISTORY, TOOL_GET_PAIR_STATS,
    TOOL_GET_BEST_WORST, TOOL_GET_DAILY_SUMMARIES, TOOL_GET_SCHEDULES,
    TOOL_GET_TRADING_RULES, TOOL_GET_FEE_INFO,
    TOOL_GET_CONFIG,
    TOOL_UPDATE_RULE, TOOL_UPDATE_TRADING_PARAM, TOOL_UPDATE_RISK_PARAM,
    TOOL_ADD_PAIR, TOOL_REMOVE_PAIR, TOOL_BLACKLIST_PAIR, TOOL_UNBLACKLIST_PAIR,
    TOOL_PAUSE_TRADING, TOOL_RESUME_TRADING, TOOL_EMERGENCY_STOP,
    TOOL_ENABLE_HIGHSTAKES, TOOL_DISABLE_HIGHSTAKES,
    TOOL_APPROVE_ITEM, TOOL_REJECT_ITEM, TOOL_CANCEL_SWAP, TOOL_CREATE_TASK,
    TOOL_SCHEDULE_REPORT, TOOL_DELETE_SCHEDULE,
]

BUILTIN_TOOL_REGISTRY: dict[str, ToolDef] = {t.name: t for t in _BUILTIN_TOOLS}
