"""
Environment & infrastructure integrity tests.

Prevents regressions like:
- docker-compose.yml referencing ${VAR} that setup.ps1 never generates
- root .env missing vars that docker-compose.yml needs for substitution
- config/.env encoding issues (non-UTF-8 bytes crash python-dotenv)
- setup.ps1 and docker-compose.yml drifting out of sync

Run with: python -m pytest tests/test_env_integrity.py -v
"""
from __future__ import annotations

import re
from pathlib import Path

import pytest

ROOT = Path(__file__).resolve().parent.parent


# ═══════════════════════════════════════════════════════════════════════════
# Helpers
# ═══════════════════════════════════════════════════════════════════════════

def _extract_compose_substitution_vars() -> set[str]:
    """Return all ${VAR} and ${VAR:-default} variable names from docker-compose.yml."""
    text = (ROOT / "docker-compose.yml").read_text(encoding="utf-8")
    return set(re.findall(r"\$\{(\w+?)(?::-[^}]*)?}", text))


def _extract_setup_root_env_vars() -> set[str]:
    """Return variable names that setup.ps1 writes to the root .env file."""
    text = (ROOT / "setup.ps1").read_text(encoding="utf-8")
    # The root .env block is between the $rootEnv = @( ... ) section
    match = re.search(r'\$rootEnv\s*=\s*@\((.*?)\)', text, re.DOTALL)
    assert match, "Could not find $rootEnv block in setup.ps1"
    block = match.group(1)
    # Extract KEY=value patterns (ignore comments and blank strings)
    return set(re.findall(r'"(\w+)=', block))


def _extract_setup_config_env_vars() -> set[str]:
    """Return variable names that setup.ps1 writes to config/.env via Append-Env."""
    text = (ROOT / "setup.ps1").read_text(encoding="utf-8")
    return set(re.findall(r'Append-Env\s+-Key\s+"(\w+)"', text))


# ═══════════════════════════════════════════════════════════════════════════
# Tests: docker-compose ↔ setup.ps1 sync
# ═══════════════════════════════════════════════════════════════════════════

class TestComposeSetupSync:
    """Ensure every ${VAR} in docker-compose.yml is generated by setup.ps1."""

    # Vars with defaults in compose (${VAR:-default}) that are safe to omit
    VARS_WITH_COMPOSE_DEFAULTS = {
        "OLLAMA_MODEL",
        "LANGFUSE_PUBLIC_KEY",
        "LANGFUSE_SECRET_KEY",
        "LANGFUSE_ADMIN_EMAIL",
        "LANGFUSE_ADMIN_NAME",
        "MINIO_ROOT_USER",
    }

    def test_all_compose_vars_in_setup_root_env(self):
        """Every ${VAR} in docker-compose.yml must appear in setup.ps1's root .env block."""
        compose_vars = _extract_compose_substitution_vars()
        root_env_vars = _extract_setup_root_env_vars()
        missing = compose_vars - root_env_vars - self.VARS_WITH_COMPOSE_DEFAULTS
        assert not missing, (
            f"docker-compose.yml references ${{VAR}} not written to root .env by setup.ps1: "
            f"{sorted(missing)}. Add them to the $rootEnv block in setup.ps1."
        )

    def test_all_compose_password_vars_in_setup_config_env(self):
        """Every password/secret var in docker-compose.yml must be generated in config/.env."""
        compose_vars = _extract_compose_substitution_vars()
        config_vars = _extract_setup_config_env_vars()
        password_vars = {v for v in compose_vars if "PASSWORD" in v or "SECRET" in v or "SALT" in v or "ENCRYPTION" in v}
        missing = password_vars - config_vars
        assert not missing, (
            f"docker-compose.yml needs passwords not generated by setup.ps1 Append-Env: "
            f"{sorted(missing)}. Add them to the infrastructure secrets step."
        )

    def test_traitor_db_password_generated(self):
        """Regression: TRAITOR_DB_PASSWORD must be generated by setup.ps1."""
        config_vars = _extract_setup_config_env_vars()
        assert "TRAITOR_DB_PASSWORD" in config_vars, (
            "TRAITOR_DB_PASSWORD missing from setup.ps1 — traitor-db will start with "
            "an empty password, making it impossible to connect after adding passwords later."
        )

    def test_traitor_db_password_in_root_env(self):
        """Regression: TRAITOR_DB_PASSWORD must be in root .env for compose substitution."""
        root_vars = _extract_setup_root_env_vars()
        assert "TRAITOR_DB_PASSWORD" in root_vars, (
            "TRAITOR_DB_PASSWORD missing from $rootEnv in setup.ps1 — "
            "docker compose will substitute it as empty."
        )


# ═══════════════════════════════════════════════════════════════════════════
# Tests: .env file encoding
# ═══════════════════════════════════════════════════════════════════════════

class TestEnvFileEncoding:
    """Prevent non-UTF-8 .env files that crash python-dotenv."""

    @pytest.mark.skipif(
        not (ROOT / "config" / ".env").exists(),
        reason="config/.env not present (CI or fresh clone)",
    )
    def test_config_env_is_valid_utf8(self):
        """config/.env must be valid UTF-8 — python-dotenv crashes on invalid bytes."""
        raw = (ROOT / "config" / ".env").read_bytes()
        # Check for BOM (shouldn't be there)
        assert not raw.startswith(b"\xef\xbb\xbf"), (
            "config/.env has a UTF-8 BOM — python-dotenv may behave unexpectedly. "
            "Re-save without BOM."
        )
        try:
            raw.decode("utf-8")
        except UnicodeDecodeError as e:
            pytest.fail(
                f"config/.env contains non-UTF-8 bytes at position {e.start}: "
                f"0x{raw[e.start]:02X}. This crashes python-dotenv. "
                f"Re-encode the file as UTF-8."
            )

    @pytest.mark.skipif(
        not (ROOT / ".env").exists(),
        reason="Root .env not present (CI or fresh clone)",
    )
    def test_root_env_is_valid_utf8(self):
        """Root .env must be valid UTF-8."""
        raw = (ROOT / ".env").read_bytes()
        try:
            raw.decode("utf-8")
        except UnicodeDecodeError as e:
            pytest.fail(
                f"Root .env contains non-UTF-8 bytes at position {e.start}: "
                f"0x{raw[e.start]:02X}. Re-encode as UTF-8."
            )


# ═══════════════════════════════════════════════════════════════════════════
# Tests: .env completeness (when files exist)
# ═══════════════════════════════════════════════════════════════════════════

class TestEnvCompleteness:
    """When .env files exist, verify they contain all required vars."""

    REQUIRED_ROOT_ENV_VARS = {
        "TRAITOR_DB_PASSWORD",
        "REDIS_PASSWORD",
        "LANGFUSE_DB_PASSWORD",
        "LANGFUSE_NEXTAUTH_SECRET",
        "LANGFUSE_SALT",
        "LANGFUSE_ENCRYPTION_KEY",
        "LANGFUSE_ADMIN_PASSWORD",
        "CLICKHOUSE_PASSWORD",
        "MINIO_ROOT_PASSWORD",
    }

    REQUIRED_CONFIG_ENV_VARS = REQUIRED_ROOT_ENV_VARS  # same set

    @pytest.mark.skipif(
        not (ROOT / ".env").exists(),
        reason="Root .env not present",
    )
    def test_root_env_has_required_vars(self):
        """Root .env must define all infrastructure password vars for compose substitution."""
        text = (ROOT / ".env").read_text(encoding="utf-8")
        defined = set(re.findall(r"^(\w+)=.+", text, re.MULTILINE))
        missing = self.REQUIRED_ROOT_ENV_VARS - defined
        assert not missing, (
            f"Root .env is missing required variables: {sorted(missing)}. "
            f"Docker Compose will substitute them as empty strings, causing container failures."
        )

    @pytest.mark.skipif(
        not (ROOT / ".env").exists(),
        reason="Root .env not present",
    )
    def test_root_env_no_empty_passwords(self):
        """No password var in root .env should have an empty value."""
        text = (ROOT / ".env").read_text(encoding="utf-8")
        for line in text.splitlines():
            if "=" not in line or line.strip().startswith("#"):
                continue
            key, _, value = line.partition("=")
            key = key.strip()
            if "PASSWORD" in key or "SECRET" in key or "SALT" in key:
                assert value.strip(), (
                    f"Root .env has empty value for {key} — "
                    f"this will cause container auth failures."
                )

    @pytest.mark.skipif(
        not (ROOT / "config" / ".env").exists(),
        reason="config/.env not present",
    )
    def test_config_env_has_required_vars(self):
        """config/.env must define all infrastructure password vars."""
        text = (ROOT / "config" / ".env").read_text(encoding="utf-8")
        defined = set(re.findall(r"^(\w+)=.+", text, re.MULTILINE))
        missing = self.REQUIRED_CONFIG_ENV_VARS - defined
        assert not missing, (
            f"config/.env is missing required variables: {sorted(missing)}. "
            f"Containers reading env_file will not get these values."
        )


# ═══════════════════════════════════════════════════════════════════════════
# Tests: docker-compose.yml structural checks
# ═══════════════════════════════════════════════════════════════════════════

class TestComposeStructure:
    """Catch structural issues in docker-compose.yml."""

    def test_no_bare_password_vars_without_default(self):
        """Password/secret vars in compose must NOT have defaults (forces explicit setup)."""
        text = (ROOT / "docker-compose.yml").read_text(encoding="utf-8")
        # Find ${PASSWORD_VAR:-default} patterns — passwords should never have defaults
        defaulted_passwords = re.findall(
            r"\$\{(\w*(?:PASSWORD|SECRET|SALT|ENCRYPTION)\w*):-([^}]+)}", text
        )
        # Filter out non-sensitive ones
        # Allow non-critical defaults (dev-only services, project init keys)
        ALLOWED_DEFAULTS = {
            "LANGFUSE_PUBLIC_KEY", "LANGFUSE_SECRET_KEY",
            "TEMPORAL_DB_PASSWORD", "TEMPORAL_DB_USER", "TEMPORAL_DB_NAME",
        }
        sensitive_defaults = [
            (var, default)
            for var, default in defaulted_passwords
            if var not in ALLOWED_DEFAULTS
        ]
        assert not sensitive_defaults, (
            f"docker-compose.yml has default values for sensitive vars: "
            f"{[(v, d) for v, d in sensitive_defaults]}. "
            f"Passwords must never have defaults — they should fail loudly if missing."
        )
